/// Flutter icons JogappsCard
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JogappsCard
///      fonts:
///       - asset: fonts/JogappsCard.ttf
///
///
///
import 'package:flutter/widgets.dart';

class JogappsCard {
  JogappsCard._();

  static const _kFontFam = 'JogappsCard';
  static const _kFontPkg = null;

  static const IconData card = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
